on:
  push:
  pull_request:

name: CI-CDN

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: docker-practice/actions-setup-docker@master
      - uses: khs1994-docker/actions-setup-lnmp@master
        with:
          lnmp_services: "laravel nginx mysql php7 redis minio"
          lrew_include: "laravel minio"
      - name: Init LNMP
        run: |
          set -x
          docker-compose --version
          lnmp-docker compose --official
          lnmp-docker services
          docker-compose --version
      - name: Setup S3(Minio)
        run: |
          set -x
          echo "MINIO_ACCESS_KEY=minioadmin" >> $LNMP_PATH/.env
          echo "MINIO_SECRET_KEY=minioadmin" >> $LNMP_PATH/.env
          echo "MINIO_REGION=us-east-1" >> $LNMP_PATH/.env
          echo "MINIO_BROWSER=off" >> $LNMP_PATH/.env

          cp $LNMP_PATH/config/nginx/minio.config $LNMP_PATH/config/nginx/minio.conf
          echo "ASSET_URL=https://minio.t.khs1994.com/laravel/asset/" >> $LNMP_PATH/lrew/laravel/.env.development

          cat <<EOF | tee -a $LNMP_PATH/lrew/laravel/.env.development
          AWS_ACCESS_KEY_ID=minioadmin
          AWS_SECRET_ACCESS_KEY=minioadmin
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=laravel
          AWS_USE_PATH_STYLE_ENDPOINT=true
          AWS_ENDPOINT=http://minio:9000
          EOF

          cat $LNMP_PATH/lrew/laravel/.env.development
      - name: Install Laravel
        env:
          ACTIONS_COMPOSER_BIN_PATH: /home/runner/.composer/vendor/bin
        run: |
          set -x
          export PATH=$ACTIONS_COMPOSER_BIN_PATH:$PATH

          lnmp-composer config -g --unset repos.packagist

          cd ..
          lnmp-laravel-by-composer new laravel 6.0
          cp -r laravel-demo/{.dockerignore,Dockerfile.backend} laravel/
          cp -r laravel-demo/.test/* laravel/
          ls -la laravel
          ls -la laravel/resources/views
          cd laravel
          lnmp-composer require --dev laravel/ui
          lnmp-composer require league/flysystem
          lnmp-composer require league/flysystem-aws-s3-v3
          lnmp-php artisan ui vue
      - name: Build Frontend
        run: |
          set -x
          cd ../laravel

          npm i
          npm run production
      - name: Test Laravel
        run: |
          set -x
          cd ../laravel

          lnmp-php artisan -V
          echo "Test Laravel"
      - name: Build Docker Image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          set -x
          cd ../laravel
          docker buildx build --load --target=laravel -t khs1994/laravel:6.0 -f Dockerfile.backend .
      - name: Up LNMP
        run: |
          set -x

          lnmp-docker up
          sleep 30
          lnmp-docker nginx-cli ls /app/laravel-docker/public || cat $LNMP_PATH/log/nginx/error.log
      - name: New S3 Bucket
        env:
          mc: docker run --rm --network host -v minio:/root/.mc minio/mc --insecure
        run: |
          set -x
          ${mc} config host add minio https://minio.t.khs1994.com minioadmin minioadmin
          ${mc} config host list minio
          ${mc} mb minio/laravel
      - name: Upload to S3(CDN)
        # 由于测试项目的 S3 位于本地，不能使用直接使用 actions
        # 若 S3 位于公网，则可以使用
        # uses: peter-evans/s3-backup@v1.0.0
        env:
          # ${{ secrets.S3_ACCESS_KEY_ID }}
          ACCESS_KEY_ID: minioadmin
          # ${{ secrets.S3_SECRET_ACCESS_KEY }}
          SECRET_ACCESS_KEY: minioadmin
          MIRROR_TARGET: laravel/asset/
          MIRROR_SOURCE: '/home/runner/work/laravel-demo/laravel/public'
          STORAGE_SERVICE_URL: 'https://minio.t.khs1994.com'
          STORAGE_SERVICE_ALIAS: 'minio'
        # with:
        #   args: --overwrite # --remove
        run: |
          set -x
          STORAGE_SERVICE_ALIAS=${STORAGE_SERVICE_ALIAS:="s3"}
          STORAGE_SERVICE_URL=${STORAGE_SERVICE_URL:="https://s3.amazonaws.com"}
          MIRROR_SOURCE=${MIRROR_SOURCE:="."}

          export mc="docker run --rm --network host -v minio:/root/.mc -v $MIRROR_SOURCE:$MIRROR_SOURCE minio/mc --insecure"
          echo "Execute mc mirror"
          ${mc} mirror --overwrite "$MIRROR_SOURCE" "$STORAGE_SERVICE_ALIAS/$MIRROR_TARGET"
      - name: Check S3 files
        env:
          mc: docker run --rm --network host -v minio:/root/.mc minio/mc --insecure
        run: |
          set -x
          ${mc} ls -r minio/laravel
          ${mc} policy set public minio/laravel
          ${mc} policy get minio/laravel
      - name: Connect
        run: |
          set -x
          docker ps -a
          curl -sSk https://laravel-docker.t.khs1994.com
          curl -sSk https://laravel-docker.t.khs1994.com/test
          curl -sSk https://laravel-docker.t.khs1994.com/test/view
          curl -sSk https://laravel-docker.t.khs1994.com/test/s3
