on:
  push:

name: CI

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          lnmp-laravel new .
      - run: |
          docker buildx build
