on:
  push:
    branches:
      - "master"
  pull_request:

name: CI

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      LNMP_CN_ENV: false
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - uses: azure/docker-login@v1
        if: |
          github.event_name == 'push'
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: test
          docker_version: "20.10"
      - uses: khs1994-docker/actions-setup-lnmp@master
        with:
          lnmp_branch: "20.10"
          lnmp_services: "laravel nginx mysql php8 redis"
          lrew_include: "laravel"
      - name: Init LNMP
        run: |
          docker compose version
          lnmp-docker services
      - name: Install Laravel
        env:
          ACTIONS_COMPOSER_BIN_PATH: /home/runner/.composer/vendor/bin
        run: |
          echo "$ACTIONS_COMPOSER_BIN_PATH" >> $GITHUB_PATH

          lnmp-composer config -g --unset repos.packagist

          cd ..
          lnmp-laravel new laravel

          cp -r laravel-demo/{Dockerfile,Dockerfile.buildkit} laravel/

          ls -la laravel

          cd laravel

          lnmp-composer require laravel/jetstream
          lnmp-php artisan jetstream:install inertia

          # sudo chown `id -u`:`id -g` -R resources public

          sudo cp -r ../laravel-demo/patch/. .
          ls -la resources/views

          lnmp-npm install

          lnmp-npm run build

          ls public/js
          ls public/css
      - name: Test Laravel
        run: |
          cd ../laravel

          lnmp-php artisan -V
      - name: Build Docker Image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          EVENT_NAME: ${{ github.event_name }}
        run: |
          cd ../laravel
          docker buildx build --load \
              --build-arg NODE_REGISTRY=https://registry.npmjs.org \
              --target=laravel \
              -t khs1994/laravel:10 \
              -f Dockerfile.buildkit .

          docker buildx build --load \
              --build-arg NODE_REGISTRY=https://registry.npmjs.org \
              --target=laravel-rootless \
              -t khs1994/laravel:10-rootless \
              -f Dockerfile.buildkit .

          if [ $EVENT_NAME = 'push' ];then
            docker push khs1994/laravel:10
            docker push khs1994/laravel:10-rootless
          fi
      - name: Up LNMP
        run: |
          lnmp-docker up
          sleep 30
          lnmp-docker nginx-cli ls /app/laravel-docker/public
      - name: Connect and Test
        run: |
          docker ps -a

          echo ::group::Test /
            curl -k https://laravel-docker.t.khs1994.com
          echo ::endgroup::

          echo ::group::Test Response
            curl -k https://laravel-docker.t.khs1994.com/test
          echo ::endgroup::

          echo ::group::Test View
            curl -k https://laravel-docker.t.khs1994.com/test/view
          echo ::endgroup::

          echo ::group::Test Queue
            curl -k https://laravel-docker.t.khs1994.com/test/queue
            sleep 2
            curl -k https://laravel-docker.t.khs1994.com/test/queue/result
          echo ::endgroup::

          echo ::group::Test Schedule
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
            sleep 55
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
          echo ::endgroup::

          docker run -i --rm --entrypoint=sh khs1994/laravel:10 -c "ls -la /app/laravel-docker"
      - name: Connect and Test Rootless
        run: |
          echo 'LNMP_LARAVEL_TAG=9-rootless' >> $LNMP_PATH/.env
          lnmp-docker up

          sleep 30
          docker ps -a

          echo ::group::Test /
            curl -k https://laravel-docker.t.khs1994.com
          echo ::endgroup::

          echo ::group::Test Response
            curl -k https://laravel-docker.t.khs1994.com/test
          echo ::endgroup::

          echo ::group::Test View
            curl -k https://laravel-docker.t.khs1994.com/test/view
          echo ::endgroup::

          echo ::group::Test Queue
            curl -k https://laravel-docker.t.khs1994.com/test/queue
            sleep 2
            curl -k https://laravel-docker.t.khs1994.com/test/queue/result
          echo ::endgroup::

          echo ::group::Test Schedule
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
            sleep 55
            curl -k https://laravel-docker.t.khs1994.com/test/schedule/result
          echo ::endgroup::

          echo ::group::Test Rootless
            curl -k https://laravel-docker.t.khs1994.com/test/rootless/result
          echo ::endgroup::

          docker run -i --rm --entrypoint=sh khs1994/laravel:10-rootless -c "ls -la /app/laravel-docker"
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
