on:
  push:
    branches:
      - "master"
  pull_request:

name: CI

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - uses: docker-practice/actions-setup-docker@master
      - uses: khs1994-docker/actions-setup-lnmp@master
        with:
          lnmp_services: "laravel nginx mysql php7 redis"
          lrew_include: "laravel"
      - name: Init LNMP
        run: |
          set -x
          docker-compose --version
          lnmp-docker compose --official
          lnmp-docker services
          docker-compose --version
      - name: Install Laravel
        env:
          ACTIONS_COMPOSER_BIN_PATH: /home/runner/.composer/vendor/bin
        run: |
          set -x

          echo "::add-path::$ACTIONS_COMPOSER_BIN_PATH"

          lnmp-composer config -g --unset repos.packagist

          cd ..
          lnmp-laravel new laravel 7

          cp -r laravel-demo/{Dockerfile,Dockerfile.buildkit} laravel/

          ls -la laravel
          ls -la laravel/resources/views
          cd laravel
          lnmp-composer require laravel/ui
          # 此步骤会重置 webpack.mix.js
          lnmp-php artisan ui vue

          cp -r ../laravel-demo/.patch/. .

          lnmp-npm install
          lnmp-npm install laravel-mix-versionhash --save
          lnmp-npm run dev
      - name: Test Laravel
        run: |
          set -x
          cd ../laravel

          lnmp-php artisan -V
      - name: Build Docker Image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          set -x
          cd ../laravel
          docker buildx build --load \
              --build-arg NODE_REGISTRY=https://registry.npmjs.org \
              --target=laravel \
              -t khs1994/laravel:7 \
              -f Dockerfile.buildkit .
      - name: Up LNMP
        run: |
          set -x

          lnmp-docker up
          sleep 30
          lnmp-docker nginx-cli ls /app/laravel-docker/public
      - name: Connect
        run: |
          set -x
          sleep 30
          docker ps -a
          curl -k https://laravel-docker.t.khs1994.com
          curl -k https://laravel-docker.t.khs1994.com/test
          curl -k https://laravel-docker.t.khs1994.com/test/view

          docker run -i --rm --entrypoint=sh khs1994/laravel:7 -c "ls -la /app/laravel-docker"
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v2
