on:
  push:
  pull_request:

name: CI

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          set -x
          sudo mkdir -p /data
          sudo chown `id -u`:`id -g` -R /data
          git clone --depth=1 -b 19.03 https://github.com/khs1994-docker/lnmp /data/lnmp
      - env:
          LNMP_PATH: /data/lnmp
          ACTIONS_COMPOSER_BIN_PATH: /home/runner/.composer/vendor/bin
        run: |
          set -x
          export PATH=$ACTIONS_COMPOSER_BIN_PATH:$LNMP_PATH:$LNMP_PATH/bin:$PATH

          QUITE=true lnmp-docker
          QUITE=true lnmp-docker compose --official
          docker-compose --version

          cd ..
          lnmp-laravel-by-composer new laravel 6.0
          cp -r laravel-demo/ laravel/
          ls -la laravel
          cd laravel
      - name: Up
        env:
          LNMP_PATH: /data/lnmp
        run: |
          set -x
          export PATH=$LNMP_PATH:$LNMP_PATH/bin:$PATH

          lnmp-php artisan -V
          docker buildx build --load --target=laravel -t khs1994/laravel:6.0 -f Dockerfile.buildkit .
          export LNMP_SERVICES="laravel nginx mysql php7 redis"
          export LREW_INCLUDE="laravel"
          lnmp-docker up
      - name: Connect
        run: |
          set -x
          sleep 30
          docker ps -a
          curl -k https://laravel-docker.t.khs1994.com
